config/routes.rb
Rails.application.routes.draw do

  get 'index' => "home#index"
  get 'about' => "home#about"
  root "projects#index"

  resources :projects do
    resources :tasks, only: [:create, :destroy, :update]
    resources :discussions, only: [:create, :edit, :destroy]
    resources :favourites, only: [:create, :destroy]
  end
  resources :tasks, only: [:edit, :update]  do
   post :sort, on: :collection
  end

  resources :favourites, only: [:index]

  resources :discussions, only: [:show, :update, :edit] do
    resources :comments, only: [:create, :destroy, :update, :edit]
  end

  resources :users, only: [:new, :create, :edit, :update] do

  end
  get "users/:id/update-password" => "users#edit_password", as: :edit_password
  patch "users/:id/update-password" => "users#update_password", as: :update_password

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  namespace :api, defaults: {format: :json } do
    namespace :v1 do
      resources :projects, only: [:index, :show, :create] do
        resources :tasks, only: [:create]
      end
      resources :discussions, only: [:show]
    end
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  get "/auth/github", as: :sign_in_with_github
  get "/auth/github/callback" => "callbacks#github"

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :discussion
  belongs_to :user
  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: [:edit, :update, :destroy]
  before_action :authenticate_user


  def create
    @discussion = Discussion.find(params[:discussion_id])
    @comment = Comment.new(comment_params)
    @comment.discussion = @discussion
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        DiscussionsMailer.notify_discussion_owner(@comment).deliver_later unless @discussion.user == current_user
        format.html { redirect_to discussion_path(@discussion), flash: { success:  "Comment created" } }
        format.js { render :comment_create_success }
      else

        format.html { render "discussions/show" }
        format.js { render :comment_create_failure}
      end
    end
  end

  def edit
    @discussion = @comment.discussion
    respond_to do |format|
      format.js { render :edit_comment}
    end
  end

  def update
    # @discussion = Comment.find(params[:id])
    @discussion = @comment.discussion
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to discussion_path(@discussion), flash: { success: "Comment updated..."}}
        format.js { render :update_comment_success }
      else
        format.js { render :update_comment_failure }
      end
    end
  end

  def destroy
    @discussion = @comment.discussion
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to discussion_path(params[:discussion_id]), flash: {danger: "Comment Deleted" } }
      format.js { render }
    end
  end

    private

      def find_comment
        @comment = Comment.find(params[:id])
      end

      def comment_params
        params.require(:comment).permit([:body])
      end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id = "<%= dom_id(comment) %>">
  <%= comment.body %>
  <%= link_to "Edit", edit_discussion_comment_path(@discussion, comment), remote: true %>  
  <%= link_to "Delete", discussion_comment_path(@discussion, comment),
                        method: :delete,
                        remote: true,
                        data: { confirm: "Are you sure?" } %>
</li>

app/views/comments/_form.html.erb
<section id="<%= dom_id(@comment) %>">
<% if @comment.errors.any? %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3 alert alert-danger">
        <p>The form contains <strong><%= pluralize(@comment.errors.count, "error") %></strong>.</p>
      <ul>
        <% @comment.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>
  <div class="row">
    <div class="form-group-lg col-md-6 col-md-offset-3">
      <%# binding.pry %>
      <%= form_for [@discussion, @comment], remote: true do |f|  %>
      <div class = "form-group">
        <%# f.label :body %>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class = "form-group">
        <%= f.submit class: "btn btn-primary btn-block" %>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/comments/comment_create_failure.js.erb
$("#comments-form").html("<%= j render 'form' %>")

app/views/comments/comment_create_success.js.erb
$("#comments_looper").prepend("<%= j render 'comments/comment', comment: @comment %>")
<% @comment = Comment.new %>
$("#comments-form").html("<%= j render 'form' %>")
$("#comment_body").val("");

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").fadeOut(500, function() {
  $(this).remove();
});

app/views/comments/edit.html.erb
<h1>Edit your comment...</h1>

<!-- DISPLAY ERRORS -->
<% if @comment.errors.any? %>
<ul>
  <% @comment.errors.full_messages.each do |error_msg| %>
    <li style = "color: red"><%= error_msg %></li>
  <% end %>
</ul>
<% end %>
<!-- FORM FOR COMMENT -->
<%= form_for [@discussion, @comment] do |f|  %>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit_comment.js.erb
$("#<%= dom_id(@comment) %>").replaceWith("<%= j render 'comments/form' %>");

app/views/comments/update_comment_failure.js.erb
$("#<%= dom_id(@comment) %>").html("<%= j render 'form' %>")

app/views/comments/update_comment_success.js.erb
$("#<%= dom_id(@comment) %>").replaceWith("<%= j render 'comments/comment', comment: @comment %>")