config/routes.rb
Rails.application.routes.draw do

  get 'index' => "home#index"
  get 'about' => "home#about"
  root "projects#index"

  resources :projects do
    resources :tasks, only: [:create, :destroy, :update]
    resources :discussions, only: [:create, :edit, :destroy]
    resources :favourites, only: [:create, :destroy]
  end
  resources :tasks, only: [:edit, :update]  do
   post :sort, on: :collection
  end

  resources :favourites, only: [:index]

  resources :discussions, only: [:show, :update, :edit] do
    resources :comments, only: [:create, :destroy, :update, :edit]
  end

  resources :users, only: [:new, :create, :edit, :update] do

  end
  get "users/:id/update-password" => "users#edit_password", as: :edit_password
  patch "users/:id/update-password" => "users#update_password", as: :update_password

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  namespace :api, defaults: {format: :json } do
    namespace :v1 do
      resources :projects, only: [:index, :show, :create] do
        resources :tasks, only: [:create]
      end
      resources :discussions, only: [:show]
    end
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  get "/auth/github", as: :sign_in_with_github
  get "/auth/github/callback" => "callbacks#github"

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_create :generate_api_key

  has_many :projects, dependent: :destroy
  has_many :discussions, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :tasks, dependent: :nullify


  has_many :favourites, dependent: :destroy
  has_many :favourite_projects, through: :favourites, source: :project

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  # temporarily store password in memory
  # attr_accessor :password
  # attr_accessor :password_confirmation
  # add ^^ attributes for us.

  validate :password_length
  validates :password, length: { minimum: 5 }, on: :create
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
            uniqueness: true,
            format: VALID_EMAIL_REGEX, unless: :from_oauth?

  # def authenticate_password(params)
  #   self.authenticate(user_params[:current_password])) && (user_params[:password] == user_params[:password_confirmation])
  # end
  # def update_password(params)
#
  # end

  def from_oauth?
    provider.present? && uid.present?
  end

  def full_name
    "#{first_name} #{last_name}".titleize.strip
  end

  def self.find_twitter_user(omniauth_data)
    where(provider: "twitter", uid: omniauth_data["uid"]).first
  end

  def self.create_from_twitter(twitter_data)
    name = twitter_data["info"]["name"].split(" ")
    User.create(provider: "twitter",
                uid: twitter_data["uid"],
                first_name: name[0], last_name: name[1],
                password: SecureRandom.hex,
                twitter_token: twitter_data["credentials"]["token"],
                twitter_secret: twitter_data["credentials"]["secret"],
                twitter_raw_data: twitter_data )
  end

  def self.find_github_user(omniauth_data)
    where(provider: "github", uid: omniauth_data["uid"]).first
  end

  def self.create_from_github(github_data)
    name = github_data["info"]["name"].split(" ")
    User.create(provider: "github",
                uid: github_data["uid"],
                first_name: name[0], last_name: name[1],
                password: SecureRandom.hex,
                github_token: github_data["credentials"]["token"],
                github_extra_data: github_data["extra"]["raw_info"])
  end

  private

    def password_length
      if password.present?
        true unless password.length <= 6
      elsif !password.present?
        true
      else
        errors.add(:password, "must be longer than 6 characters")
        # false
        # use false if doing a before_update callback
      end
    end

    def generate_api_key
      self.api_key = SecureRandom.hex(32)
      while User.exists?(api_key: self.api_key)
        self.api_key = SecureRandom.hex(32)
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy, :update_password]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to root_path, flash: { success:  "User created" }
    else
      flash[:danger] = "User not created"
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, flash: { info:  "User Updated" }
    else
      flash[:danger] = "nope"
      render :edit
    end
  end

  def edit_password
    @user = User.find(params[:id])
  end

  def update_password
    if (@user.authenticate(user_params[:current_password])) && (user_params[:password] == user_params[:password_confirmation]) && @user.update(password: user_params[:password])
      redirect_to root_path, flash: { success: "Project Updated!" }
    else
      flash[:warning] = "Invalid Combination"
      render :edit_password
    end
  end

    private

      def user_params
        params.require(:user).permit([:first_name, :last_name, :email, :password, :password_confirmation, :current_password])
      end

      def find_user
        @user = User.find(params[:id])
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form_user.html.erb
<% if @user.errors.any? %>
<div class="row">
  <div class="col-md-6 col-md-offset-3 alert alert-danger">
    <p>The form contains <strong><%= pluralize(@user.errors.count, "error") %></strong>.</p>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  </div>
</div>
<% end %>

<div class="row">
<div class="form-group-lg col-md-6 col-md-offset-3">
<%= form_for @user do |f| %>
  <div class = "form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class = "form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
<div class = "form-group">
    <%= f.label :email  %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
  <div class = "form-group">
    <%= f.label :password  %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class = "form-group">
    <%= f.label :password_confirmation  %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class = "form-group">
    <%= f.submit "Create Account", class: "btn btn-primary btn-block" %>
  </div>
<% end %>
</div>
</div>

app/views/users/edit.html.erb
<h1 class = "text-lg-center title">Update Your Information</h1>

<% if @user.errors.any? %>
<div class="row">
  <div class="col-md-6 col-md-offset-3 alert alert-danger">
    <p>The form contains <strong><%= pluralize(@user.errors.count, "error") %></strong>.</p>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  </div>
</div>
<% end %>


<div class="row">
  <div class="form-group-lg col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <div class = "form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
      <div class = "form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
      <div class = "form-group">
        <%= f.label :email  %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class = "form-group">
        <%= f.submit "update ^_^", class: "btn btn-info-outline btn-block" %>
      </div>
      <p><%= link_to "change your password?", edit_password_path(@user) %></p>
    <% end %>
  </div>
</div>

app/views/users/edit_password.html.erb
<h1 class = "title text-lg-center">Edit Your Password</h1>

<p><%# link_to "Change your password", edit_password_path(@user) %></p>

<% if @user.errors.any? %>
<div class="row">
  <div class="col-md-6 col-md-offset-3 alert alert-danger">
<ul>
  <% @user.errors.full_messages.each do |error| %>
  <li style = "color: red"><%= error %></li>
  <% end %>
</ul>
  </div>
</div>
<% end %>

<div class="row">
  <div class="form-group-lg col-md-6 col-md-offset-3">
    <%= form_for(@user, url: update_password_path(@user)) do |f| %>
    <div class = "form-group">
    <%= f.label :current_password, "Current Password"%>
    <%= f.password_field :current_password, class: "form-control" %>
    </div>
    <div class = "form-group">
    <%= f.label :password, "New Password" %>
    <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class = "form-group">
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class = "form-group">
    <%= f.submit "Update Password", class: "btn btn-info-outline btn-block" %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1 class = "text-lg-center title">Sign Up</h1>
<%= render "form_user" %>