config/routes.rb
Rails.application.routes.draw do

  get 'index' => "home#index"
  get 'about' => "home#about"
  root "projects#index"

  resources :projects do
    resources :tasks, only: [:create, :destroy, :update]
    resources :discussions, only: [:create, :edit, :destroy]
    resources :favourites, only: [:create, :destroy]
  end
  resources :tasks, only: [:edit, :update]  do
   post :sort, on: :collection
  end

  resources :favourites, only: [:index]

  resources :discussions, only: [:show, :update, :edit] do
    resources :comments, only: [:create, :destroy, :update, :edit]
  end

  resources :users, only: [:new, :create, :edit, :update] do

  end
  get "users/:id/update-password" => "users#edit_password", as: :edit_password
  patch "users/:id/update-password" => "users#update_password", as: :update_password

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  namespace :api, defaults: {format: :json } do
    namespace :v1 do
      resources :projects, only: [:index, :show, :create] do
        resources :tasks, only: [:create]
      end
      resources :discussions, only: [:show]
    end
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  get "/auth/github", as: :sign_in_with_github
  get "/auth/github/callback" => "callbacks#github"

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  mount_uploaders :images, ImagesUploader

  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :comments, through: :discussions

  has_many :favourites, dependent: :destroy
  has_many :favouriting_users, through: :favourites, source: :user

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 5 }
  validate  :future_due_date



  def favourite_for(user)
    favourites.find_by(user_id: user)
  end


  private

    def future_due_date
      if self.due_date
       self.due_date > Date.yesterday ? true : errors.add(:due_date, "must be in the future!")
      end
    end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::BaseController

  def index
    @projects = Project.order("created_at DESC").limit(2)
    render json: @projects
  end

  def show
    @project = Project.find(params[:id])
    render json: @project
  end


def create
  project_params = params.require(:project).permit(:title, :description, :due_date)
  project = Project.new(project_params)
  project.user = @user
  if project.save
    head :ok
  else
    render json: { errors: project.errors.full_messages }
  end
end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def index
    @projects = Project.order("created_at DESC").page(params[:page]).per(7)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      flash[:success] = "Project added"
      redirect_to project_path(@project)
    else
      flash[:warning] = "Project unsuccessfully added"
      render :new
    end
  end

  def show
    @task = Task.new
    @discussion = Discussion.new
    # @tasks = @project.tasks.order("created_at DESC")
    # display complete/incomplete tasks
    @tasks = @project.tasks.order(:position)
    # @tasks_done = @project.tasks.where(["done = ?", true]).order("created_at DESC")
    # @tasks_not_done = @project.tasks.where(["done = ?", false]).order("created_at DESC")
    @discussions = @project.discussions.order("created_at DESC")
  end

  def edit
  end

  def update
    @project.slug = nil
    if @project.update(project_params)
      redirect_to(project_path(@project), flash: { success:  "Project Updated"})
    else
      flash[:warning] = "Update was not successful"
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to((root_path), flash: { danger: "Project Removed!" })
  end


      private

        def project_params
          params.require(:project).permit([:title, :description, :due_date, {images: [] }])
        end

        def find_project
          @project = Project.friendly.find(params[:id])
        end

        def authorize_user
          unless can? :manage, @project
          redirect_to root_path , flash: { info: "Access Denied" }
          end
        end

end

app/helpers/api/v1/projects_helper.rb
module Api::V1::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
<div class="row">
  <div class="col-md-6 col-md-offset-3 alert alert-danger">
    <p>The form contains <strong><%= pluralize(@project.errors.count, "error") %></strong>.</p>
  <ul>
    <% @project.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  </div>
</div>
<% end %>
<div class="row">
  <div class="form-group-lg col-md-6 col-md-offset-3">
    <%= form_for @project do |f| %>
    <div class = "form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class = "form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class = "form-group">
    <%= f.label :due_date %>
    <%= f.date_select :due_date, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.file_field :images, multiple: true, class: "form-control" %>
    </div>
    <div class = "form-group">
      <%= submit_tag "Add Project", class: "btn btn-primary btn-block"  %>
    </div>
    <% end %>
  </div>
</div>
<!-- expression evaluates, saved into variable, not going to run whole expression again. isn't going to recreate it. type of caching.   -->

app/views/projects/edit.html.erb
<h1>EDIT A PROJECT</h1>
<%= render "form" %>

app/views/projects/index.html.erb
<h1 class = "text-lg-center title project-list">All Projects (<%= @projects.length %>)</h1>

<% if @projects %>
<div class="row list-all-projects">
  <div class="form-group-lg col-md-6 col-md-offset-3 inner-projects">
    <table class="table">
      <% @projects.each do |project| %>
        <tr>
          <td class = "text-lg-center"><%= link_to project.title, project_path(project) %></span></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<section class="row pagination-footer">
  <div class="col-md-6 col-md-offset-3 text-lg-center ">
    <%= paginate @projects %>
  </div>
</section>
<% end %>

app/views/projects/new.html.erb
<h1 class = "text-lg-center title project-list">Add a new project</h1>
<%= render "form" %>

app/views/projects/show.html.erb
<h1 class = "title text-lg-center"><%= @project.title %></h1>
  <div class="row">
    <div class="form-group-lg col-md-6 col-md-offset-3">
      <p> <%= @project.description %></p>
      <h4><%= @project.due_date %></h4>
      <p><%= link_to "EDIT", edit_project_path(@project) %></p>
      <p><%= link_to "DELETE", project_path(@project), method: :delete, data: { confirm: "Are you sure?"} %></p>
      <% if @project.user != current_user  %>
        <% favourite = @project.favourite_for(current_user) %>
          <% if favourite %>
          <%= link_to fa_icon("heart"), project_favourite_path(@project, favourite), method: :delete %>
          <% else %>
          <%= link_to fa_icon("heart-o"), project_favourites_path(@project), method: :post %>
        <% end %>
        <%= @project.favourites.count %>
      <% end  %>
    </div>
  </div>
<hr>
<div class="row">
  <div class="form-group-lg col-md-6">
    <h3>Add a Task </h3>
      <%= render "tasks/form" %>
  </div>
  <div class="col-md-6">
    <%= render "tasks/tasks" %>
  </div>
</div>


<!-- LIST ALL DISCUSSIONS -->
<% if @discussions.present? %>
<h2 class = "lg">ALL DISCUSSIONS: </h2>
  <ul>
  <% @discussions.each do |discussion| %>
  <li><%= link_to "#{discussion.title}", discussion_path(discussion) %>
      <%= link_to "Edit", edit_project_discussion_path(@project, discussion) %>
      <%= link_to "Delete", project_discussion_path(@project, discussion), method: :delete, data: { confirm: "Are you sure??"} %>
      </li>

  <% end %>
</ul>
<% end %>

<!-- ADD A DISCUSSION -->
<h2 class = "text-lg-center title">Add a Discussion </h2>
<!--ERROR MESSAGES FOR DISCUSSION -->
<% if @discussion && @discussion.errors.any? %>
<div class="row">
  <div class="col-md-6 col-md-offset-3 alert alert-danger">
    <p>The form contains <strong><%= pluralize(@discussion.errors.count, "error") %></strong>.</p>
    <ul>
      <% @discussion.errors.full_messages.each do |error| %>
      <li><%= error %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>
<!-- FORM FOR DISCUSSION -->
<div class="row">
    <div class="form-group-lg col-md-6 col-md-offset-3">
      <%= form_for [@project, (@discussion || Discussion.new)] do |f| %>
      <div class = "form-group">
        <% f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class = "form-group">
        <% f.label :body %>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class = "form-group">
        <%= f.submit "add discussion", class: "btn btn-primary" %>
      </div>
      <% end %>
  </div>
</div>

<!-- DISPLAY ALL TASKS-->
 <%# if @tasks %>
 <!-- <h4>All Tasks ... (<%# @tasks.length %>)</h4> -->
 <!-- <ul> -->
 <%# @tasks.each do |task| %>
   <!-- <li><%# task.title  %> -->
       <%# render "done", task: task %>
       <%# link_to "Delete", [@project, task], method: :delete,
           data: { confirm: "Are you sure?"} %>
   <!-- </li> -->
   <%# end %>
 <!-- </ul> -->
 <%# end %>