config/routes.rb
Rails.application.routes.draw do

  get 'index' => "home#index"
  get 'about' => "home#about"
  root "projects#index"

  resources :projects do
    resources :tasks, only: [:create, :destroy, :update]
    resources :discussions, only: [:create, :edit, :destroy]
    resources :favourites, only: [:create, :destroy]
  end
  resources :tasks, only: [:edit, :update]  do
   post :sort, on: :collection
  end

  resources :favourites, only: [:index]

  resources :discussions, only: [:show, :update, :edit] do
    resources :comments, only: [:create, :destroy, :update, :edit]
  end

  resources :users, only: [:new, :create, :edit, :update] do

  end
  get "users/:id/update-password" => "users#edit_password", as: :edit_password
  patch "users/:id/update-password" => "users#update_password", as: :update_password

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  namespace :api, defaults: {format: :json } do
    namespace :v1 do
      resources :projects, only: [:index, :show, :create] do
        resources :tasks, only: [:create]
      end
      resources :discussions, only: [:show]
    end
  end

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"

  get "/auth/github", as: :sign_in_with_github
  get "/auth/github/callback" => "callbacks#github"

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/views/layouts/_flash.html.erb
<% if flash %>
<section class="container">
  <section class="col-md-6 col-md-offset-3 text-lg-center">
  <% flash.each do | message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end  %>
  </section>
</section>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-full navbar-light" style = "background-color: #58e7d1">
  <div class="container">

  <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2"> &#9776; </button>
  <div class="collapse navbar-toggleable-sm" id="exCollapsingNavbar2">
      <ul class="nav navbar-nav">
        <%= link_to fa_icon("briefcase", class: "tasks-fa fa-3x"), root_path %>
        <% if user_signed_in? %>
        <li class="nav-item <%= 'active' if current_page?(new_project_path) %> ">
          <%= link_to "add project", new_project_path, class: "nav-link" %>
        </li>

        <li class="nav-item <%= 'active' if current_page?(favourites_path) %> ">
          <%= link_to "favourites", favourites_path, class: "nav-link" %>
        </li>

        <li class="nav-item
            <%= 'active' if current_page?(edit_user_path(current_user)) %>">
            <%= link_to "edit profile", edit_user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(sessions_path) %>">
          <%= link_to "log out", sessions_path, method: :delete, class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item <%= 'active' if current_page?(new_user_path) %>">
          <%= link_to "sign up", new_user_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(new_session_path) %>">
          <%= link_to "sign in", new_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(new_session_path) %>">
          <%= link_to "sign in with github", sign_in_with_github_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Libre+Baskerville' rel='stylesheet' type='text/css'>
</head>
<body>
<%= render "layouts/navbar" %>
<%= render "layouts/flash" %>
  <main class="container-fluid">
<%= yield %>
</main>
</body>
</html>